services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - YOUTUBE_API=youtubeapikey
      - SEARCH_QUERY=technology 
      - MONGO_URI=mongodbconnecturi
    depends_on:
      - mongo
    networks:
      - youtube-network

  mongo:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    networks:
      - youtube-network

networks:
  youtube-network:
    driver: bridge

volumes:
  mongodb-data:
